site_name: Cluster Documentation
site_description: Documentation for normal users and system admins
site_url: https://wit543.github.io/cluster-doc/
repo_url: https://github.com/wit543/cluster-doc

nav:
  - Home: index.md
  - Slurm Basics:
      - slurm-basics.md
      - Overview: slurm/overview.md
      - Accessing the Cluster: slurm/accessing.md
      - Environment Setup: slurm/environment.md
      - Submitting Batch Jobs: slurm/batch-jobs.md
      - Running Interactive Jobs: slurm/interactive-jobs.md
      - MPI and Multi-node Jobs: slurm/mpi-multinode.md
      - Monitoring and Managing Jobs: slurm/job-management.md
      - Storage and File Systems: slurm/storage.md
      - Helpful Commands: slurm/helpful-commands.md
      - Getting Help: slurm/help.md
  - Linux Basics: linux-basics.md
  - Slurm Basics: slurm-basics.md
  - IST-CLUSTER Guide: ist-cluster.md
  - Using Modules: modules.md
  - Apptainer: apptainer.md
  - Singularity: singularity.md
  - Editors and Tmux: tools/editors-and-tmux.md
  - File Transfer: tools/file-transfer.md
  - SSH Tunneling: tools/ssh-tunneling.md
  - Scripts:
      - scripts/index.md
      - Convert sinfo output: scripts/sinfo-to-page.md

theme:
  name: material
  custom_dir: docs/overrides
  logo: images/logo_vistec.png
  favicon: images/favicon.png
  language: en
  features:
    - navigation.sections
    - toc.integrate
    - search.suggest
    - sitemap
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Fira Code
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: dracula
      primary: deep purple
      accent: pink
      toggle:
        icon: material/ghost
        name: Switch to Dracula mode
    - scheme: high-contrast
      primary: black
      accent: yellow
      toggle:
        icon: material/eye
        name: Switch to high contrast mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized
  - minify

extra_javascript:
  - javascripts/accessibility.js

extra_templates:
  - robots.txt

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wit543/cluster-doc


extra_css:
  - stylesheets/extra.css

