backend:
  name: git-gateway
  branch: main

media_folder: "docs/uploads"
public_folder: "/uploads"

collections:
  - name: pages
    label: Pages
    folder: docs
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: scripts
    label: Scripts
    folder: docs/scripts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Script File", name: "file", widget: "file" }
